[package]
name = "receiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.3.2"
embedded-hal = "0.2.7"
sx127x_lora = "0.3.1"
rppal = "0.14.0"